NASDAQ_100 = [
    {"ticker": "AAPL",  "name": "Apple"},
    {"ticker": "MSFT",  "name": "Microsoft"},
    {"ticker": "NVDA",  "name": "NVIDIA"},
    {"ticker": "AMZN",  "name": "Amazon"},
    {"ticker": "META",  "name": "Meta Platforms"},
    {"ticker": "GOOGL", "name": "Alphabet A"},
    {"ticker": "GOOG",  "name": "Alphabet C"},
    {"ticker": "TSLA",  "name": "Tesla"},
    {"ticker": "AVGO",  "name": "Broadcom"},
    {"ticker": "COST",  "name": "Costco"},
    {"ticker": "NFLX",  "name": "Netflix"},
    {"ticker": "ASML",  "name": "ASML"},
    {"ticker": "AMD",   "name": "Advanced Micro Devices"},
    {"ticker": "QCOM",  "name": "Qualcomm"},
    {"ticker": "INTU",  "name": "Intuit"},
    {"ticker": "TXN",   "name": "Texas Instruments"},
    {"ticker": "CMCSA", "name": "Comcast"},
    {"ticker": "AMGN",  "name": "Amgen"},
    {"ticker": "ISRG",  "name": "Intuitive Surgical"},
    {"ticker": "HON",   "name": "Honeywell"},
    {"ticker": "BKNG",  "name": "Booking Holdings"},
    {"ticker": "VRTX",  "name": "Vertex Pharmaceuticals"},
    {"ticker": "REGN",  "name": "Regeneron"},
    {"ticker": "MU",    "name": "Micron Technology"},
    {"ticker": "ADI",   "name": "Analog Devices"},
    {"ticker": "PANW",  "name": "Palo Alto Networks"},
    {"ticker": "GILD",  "name": "Gilead Sciences"},
    {"ticker": "LRCX",  "name": "Lam Research"},
    {"ticker": "KLAC",  "name": "KLA Corporation"},
    {"ticker": "MELI",  "name": "MercadoLibre"},
    {"ticker": "CTAS",  "name": "Cintas"},
    {"ticker": "CRWD",  "name": "CrowdStrike"},
    {"ticker": "MDLZ",  "name": "Mondelez"},
    {"ticker": "SNPS",  "name": "Synopsys"},
    {"ticker": "CDNS",  "name": "Cadence Design"},
    {"ticker": "CSX",   "name": "CSX Corporation"},
    {"ticker": "ORLY",  "name": "O'Reilly Automotive"},
    {"ticker": "ADSK",  "name": "Autodesk"},
    {"ticker": "FTNT",  "name": "Fortinet"},
    {"ticker": "PCAR",  "name": "PACCAR"},
    {"ticker": "ABNB",  "name": "Airbnb"},
    {"ticker": "TEAM",  "name": "Atlassian"},
    {"ticker": "MCHP",  "name": "Microchip Technology"},
    {"ticker": "AEP",   "name": "American Electric Power"},
    {"ticker": "WDAY",  "name": "Workday"},
    {"ticker": "ROP",   "name": "Roper Technologies"},
    {"ticker": "NXPI",  "name": "NXP Semiconductors"},
    {"ticker": "IDXX",  "name": "IDEXX Laboratories"},
    {"ticker": "CPRT",  "name": "Copart"},
    {"ticker": "ROST",  "name": "Ross Stores"},
    {"ticker": "MNST",  "name": "Monster Beverage"},
    {"ticker": "KHC",   "name": "Kraft Heinz"},
    {"ticker": "PAYX",  "name": "Paychex"},
    {"ticker": "ODFL",  "name": "Old Dominion Freight"},
    {"ticker": "FAST",  "name": "Fastenal"},
    {"ticker": "VRSK",  "name": "Verisk Analytics"},
    {"ticker": "CTSH",  "name": "Cognizant"},
    {"ticker": "ON",    "name": "ON Semiconductor"},
    {"ticker": "EA",    "name": "Electronic Arts"},
    {"ticker": "DDOG",  "name": "Datadog"},
    {"ticker": "ZS",    "name": "Zscaler"},
    {"ticker": "ANSS",  "name": "Ansys"},
    {"ticker": "BIIB",  "name": "Biogen"},
    {"ticker": "ILMN",  "name": "Illumina"},
    {"ticker": "DXCM",  "name": "DexCom"},
    {"ticker": "EBAY",  "name": "eBay"},
    {"ticker": "TTD",   "name": "The Trade Desk"},
    {"ticker": "CEG",   "name": "Constellation Energy"},
    {"ticker": "EXC",   "name": "Exelon"},
    {"ticker": "XEL",   "name": "Xcel Energy"},
    {"ticker": "GEHC",  "name": "GE HealthCare"},
    {"ticker": "FANG",  "name": "Diamondback Energy"},
    {"ticker": "BKR",   "name": "Baker Hughes"},
    {"ticker": "DLTR",  "name": "Dollar Tree"},
    {"ticker": "ZM",    "name": "Zoom"},
    {"ticker": "MTCH",  "name": "Match Group"},
    {"ticker": "RIVN",  "name": "Rivian"},
    {"ticker": "LCID",  "name": "Lucid Group"},
    {"ticker": "WBD",   "name": "Warner Bros. Discovery"},
    {"ticker": "SIRI",  "name": "Sirius XM"},
]

KOSPI_100 = [
    {"ticker": "005930.KS", "name": "삼성전자"},
    {"ticker": "000660.KS", "name": "SK하이닉스"},
    {"ticker": "207940.KS", "name": "삼성바이오로직스"},
    {"ticker": "005380.KS", "name": "현대차"},
    {"ticker": "000270.KS", "name": "기아"},
    {"ticker": "068270.KS", "name": "셀트리온"},
    {"ticker": "035420.KS", "name": "NAVER"},
    {"ticker": "051910.KS", "name": "LG화학"},
    {"ticker": "006400.KS", "name": "삼성SDI"},
    {"ticker": "028260.KS", "name": "삼성물산"},
    {"ticker": "012330.KS", "name": "현대모비스"},
    {"ticker": "066570.KS", "name": "LG전자"},
    {"ticker": "003550.KS", "name": "LG"},
    {"ticker": "032830.KS", "name": "삼성생명"},
    {"ticker": "017670.KS", "name": "SK텔레콤"},
    {"ticker": "030200.KS", "name": "KT"},
    {"ticker": "086790.KS", "name": "하나금융지주"},
    {"ticker": "105560.KS", "name": "KB금융"},
    {"ticker": "055550.KS", "name": "신한지주"},
    {"ticker": "034730.KS", "name": "SK"},
    {"ticker": "005490.KS", "name": "POSCO홀딩스"},
    {"ticker": "003670.KS", "name": "포스코퓨처엠"},
    {"ticker": "009150.KS", "name": "삼성전기"},
    {"ticker": "018260.KS", "name": "삼성에스디에스"},
    {"ticker": "096770.KS", "name": "SK이노베이션"},
    {"ticker": "011200.KS", "name": "HMM"},
    {"ticker": "010130.KS", "name": "고려아연"},
    {"ticker": "000810.KS", "name": "삼성화재"},
    {"ticker": "047050.KS", "name": "포스코인터내셔널"},
    {"ticker": "009830.KS", "name": "한화솔루션"},
    {"ticker": "010950.KS", "name": "S-Oil"},
    {"ticker": "024110.KS", "name": "기업은행"},
    {"ticker": "000100.KS", "name": "유한양행"},
    {"ticker": "035720.KS", "name": "카카오"},
    {"ticker": "352820.KS", "name": "하이브"},
    {"ticker": "036570.KS", "name": "엔씨소프트"},
    {"ticker": "251270.KS", "name": "넷마블"},
    {"ticker": "006800.KS", "name": "미래에셋증권"},
    {"ticker": "032640.KS", "name": "LG유플러스"},
    {"ticker": "011070.KS", "name": "LG이노텍"},
    {"ticker": "161390.KS", "name": "한국타이어앤테크놀로지"},
    {"ticker": "051900.KS", "name": "LG생활건강"},
    {"ticker": "090430.KS", "name": "아모레퍼시픽"},
    {"ticker": "011170.KS", "name": "롯데케미칼"},
    {"ticker": "004020.KS", "name": "현대제철"},
    {"ticker": "000720.KS", "name": "현대건설"},
    {"ticker": "010140.KS", "name": "삼성중공업"},
    {"ticker": "042660.KS", "name": "한화오션"},
    {"ticker": "329180.KS", "name": "HD현대중공업"},
    {"ticker": "267250.KS", "name": "HD현대"},
    {"ticker": "078930.KS", "name": "GS"},
    {"ticker": "071050.KS", "name": "한국금융지주"},
    {"ticker": "015760.KS", "name": "한국전력"},
    {"ticker": "000830.KS", "name": "삼성C&T"},
    {"ticker": "316140.KS", "name": "우리금융지주"},
    {"ticker": "003490.KS", "name": "대한항공"},
    {"ticker": "020150.KS", "name": "롯데에너지머티리얼즈"},
    {"ticker": "034020.KS", "name": "두산에너빌리티"},
    {"ticker": "064350.KS", "name": "현대로템"},
    {"ticker": "012450.KS", "name": "한화에어로스페이스"},
]
