NASDAQ_200 = [
    # Mega cap
    {"ticker": "AAPL",  "name": "Apple"},
    {"ticker": "MSFT",  "name": "Microsoft"},
    {"ticker": "NVDA",  "name": "NVIDIA"},
    {"ticker": "AMZN",  "name": "Amazon"},
    {"ticker": "META",  "name": "Meta Platforms"},
    {"ticker": "GOOGL", "name": "Alphabet A"},
    {"ticker": "GOOG",  "name": "Alphabet C"},
    {"ticker": "TSLA",  "name": "Tesla"},
    {"ticker": "AVGO",  "name": "Broadcom"},
    {"ticker": "COST",  "name": "Costco"},
    # Large cap tech
    {"ticker": "NFLX",  "name": "Netflix"},
    {"ticker": "ADBE",  "name": "Adobe"},
    {"ticker": "CSCO",  "name": "Cisco Systems"},
    {"ticker": "INTC",  "name": "Intel"},
    {"ticker": "AMAT",  "name": "Applied Materials"},
    {"ticker": "AMD",   "name": "Advanced Micro Devices"},
    {"ticker": "QCOM",  "name": "Qualcomm"},
    {"ticker": "ASML",  "name": "ASML"},
    {"ticker": "MU",    "name": "Micron Technology"},
    {"ticker": "ADI",   "name": "Analog Devices"},
    {"ticker": "LRCX",  "name": "Lam Research"},
    {"ticker": "KLAC",  "name": "KLA Corporation"},
    {"ticker": "MRVL",  "name": "Marvell Technology"},
    {"ticker": "NXPI",  "name": "NXP Semiconductors"},
    {"ticker": "MCHP",  "name": "Microchip Technology"},
    {"ticker": "ON",    "name": "ON Semiconductor"},
    {"ticker": "SWKS",  "name": "Skyworks Solutions"},
    {"ticker": "QRVO",  "name": "Qorvo"},
    {"ticker": "MPWR",  "name": "Monolithic Power Systems"},
    {"ticker": "SMCI",  "name": "Super Micro Computer"},
    # Software / Cloud
    {"ticker": "INTU",  "name": "Intuit"},
    {"ticker": "SNPS",  "name": "Synopsys"},
    {"ticker": "CDNS",  "name": "Cadence Design"},
    {"ticker": "ADSK",  "name": "Autodesk"},
    {"ticker": "WDAY",  "name": "Workday"},
    {"ticker": "PANW",  "name": "Palo Alto Networks"},
    {"ticker": "CRWD",  "name": "CrowdStrike"},
    {"ticker": "FTNT",  "name": "Fortinet"},
    {"ticker": "ZS",    "name": "Zscaler"},
    {"ticker": "DDOG",  "name": "Datadog"},
    {"ticker": "ANSS",  "name": "Ansys"},
    {"ticker": "TEAM",  "name": "Atlassian"},
    {"ticker": "OKTA",  "name": "Okta"},
    {"ticker": "MDB",   "name": "MongoDB"},
    {"ticker": "CFLT",  "name": "Confluent"},
    {"ticker": "GTLB",  "name": "GitLab"},
    {"ticker": "MANH",  "name": "Manhattan Associates"},
    {"ticker": "PCTY",  "name": "Paylocity"},
    {"ticker": "PAYC",  "name": "Paycom Software"},
    {"ticker": "ROP",   "name": "Roper Technologies"},
    {"ticker": "VRSK",  "name": "Verisk Analytics"},
    {"ticker": "CTSH",  "name": "Cognizant"},
    # Consumer / Retail
    {"ticker": "SBUX",  "name": "Starbucks"},
    {"ticker": "LULU",  "name": "Lululemon Athletica"},
    {"ticker": "ORLY",  "name": "O'Reilly Automotive"},
    {"ticker": "ROST",  "name": "Ross Stores"},
    {"ticker": "CPRT",  "name": "Copart"},
    {"ticker": "ODFL",  "name": "Old Dominion Freight"},
    {"ticker": "FAST",  "name": "Fastenal"},
    {"ticker": "CTAS",  "name": "Cintas"},
    {"ticker": "PCAR",  "name": "PACCAR"},
    {"ticker": "MNST",  "name": "Monster Beverage"},
    {"ticker": "KHC",   "name": "Kraft Heinz"},
    {"ticker": "MDLZ",  "name": "Mondelez"},
    {"ticker": "DLTR",  "name": "Dollar Tree"},
    {"ticker": "EBAY",  "name": "eBay"},
    {"ticker": "CHWY",  "name": "Chewy"},
    # Fintech / Financial
    {"ticker": "PYPL",  "name": "PayPal"},
    {"ticker": "COIN",  "name": "Coinbase Global"},
    {"ticker": "HOOD",  "name": "Robinhood Markets"},
    {"ticker": "SOFI",  "name": "SoFi Technologies"},
    {"ticker": "AFRM",  "name": "Affirm Holdings"},
    {"ticker": "UPST",  "name": "Upstart Holdings"},
    {"ticker": "PAYX",  "name": "Paychex"},
    # Growth / New Economy
    {"ticker": "PLTR",  "name": "Palantir Technologies"},
    {"ticker": "ARM",   "name": "ARM Holdings"},
    {"ticker": "APP",   "name": "AppLovin"},
    {"ticker": "DKNG",  "name": "DraftKings"},
    {"ticker": "ROKU",  "name": "Roku"},
    {"ticker": "DUOL",  "name": "Duolingo"},
    {"ticker": "BMBL",  "name": "Bumble"},
    {"ticker": "ABNB",  "name": "Airbnb"},
    {"ticker": "RIVN",  "name": "Rivian"},
    {"ticker": "LCID",  "name": "Lucid Group"},
    {"ticker": "TTD",   "name": "The Trade Desk"},
    {"ticker": "ZM",    "name": "Zoom"},
    {"ticker": "MTCH",  "name": "Match Group"},
    # Healthcare / Biotech
    {"ticker": "AMGN",  "name": "Amgen"},
    {"ticker": "GILD",  "name": "Gilead Sciences"},
    {"ticker": "VRTX",  "name": "Vertex Pharmaceuticals"},
    {"ticker": "REGN",  "name": "Regeneron"},
    {"ticker": "ISRG",  "name": "Intuitive Surgical"},
    {"ticker": "IDXX",  "name": "IDEXX Laboratories"},
    {"ticker": "DXCM",  "name": "DexCom"},
    {"ticker": "BIIB",  "name": "Biogen"},
    {"ticker": "ILMN",  "name": "Illumina"},
    {"ticker": "MRNA",  "name": "Moderna"},
    {"ticker": "BNTX",  "name": "BioNTech"},
    {"ticker": "ALNY",  "name": "Alnylam Pharmaceuticals"},
    {"ticker": "IONS",  "name": "Ionis Pharmaceuticals"},
    {"ticker": "NBIX",  "name": "Neurocrine Biosciences"},
    {"ticker": "EXAS",  "name": "Exact Sciences"},
    {"ticker": "PODD",  "name": "Insulet Corporation"},
    {"ticker": "ALGN",  "name": "Align Technology"},
    {"ticker": "HALO",  "name": "Halozyme Therapeutics"},
    {"ticker": "INSM",  "name": "Insmed"},
    {"ticker": "ACAD",  "name": "ACADIA Pharmaceuticals"},
    {"ticker": "NVCR",  "name": "NovaCure"},
    # Media / Entertainment
    {"ticker": "CMCSA", "name": "Comcast"},
    {"ticker": "WBD",   "name": "Warner Bros. Discovery"},
    {"ticker": "SIRI",  "name": "Sirius XM"},
    # Gaming
    {"ticker": "EA",    "name": "Electronic Arts"},
    {"ticker": "TTWO",  "name": "Take-Two Interactive"},
    # Industrial / Energy
    {"ticker": "HON",   "name": "Honeywell"},
    {"ticker": "TXN",   "name": "Texas Instruments"},
    {"ticker": "CSX",   "name": "CSX Corporation"},
    {"ticker": "AEP",   "name": "American Electric Power"},
    {"ticker": "CEG",   "name": "Constellation Energy"},
    {"ticker": "EXC",   "name": "Exelon"},
    {"ticker": "XEL",   "name": "Xcel Energy"},
    {"ticker": "FANG",  "name": "Diamondback Energy"},
    {"ticker": "BKR",   "name": "Baker Hughes"},
    {"ticker": "TRMB",  "name": "Trimble"},
    {"ticker": "CGNX",  "name": "Cognex"},
    # Photonics / Optics
    {"ticker": "IPGP",  "name": "IPG Photonics"},
    {"ticker": "LITE",  "name": "Lumentum Holdings"},
    {"ticker": "OLED",  "name": "Universal Display"},
    # Travel / Booking
    {"ticker": "BKNG",  "name": "Booking Holdings"},
    {"ticker": "MELI",  "name": "MercadoLibre"},
    {"ticker": "TCOM",  "name": "Trip.com Group"},
    # Chinese ADRs
    {"ticker": "BIDU",  "name": "Baidu"},
    {"ticker": "JD",    "name": "JD.com"},
    {"ticker": "NTES",  "name": "NetEase"},
    {"ticker": "PDD",   "name": "PDD Holdings"},
    {"ticker": "BILI",  "name": "Bilibili"},
    {"ticker": "IQ",    "name": "iQIYI"},
    {"ticker": "LI",    "name": "Li Auto"},
    {"ticker": "FUTU",  "name": "Futu Holdings"},
    {"ticker": "XPEV",  "name": "XPeng"},
    # Other
    {"ticker": "GEHC",  "name": "GE HealthCare"},
    {"ticker": "INVA",  "name": "Innoviva"},
    {"ticker": "MSTR",  "name": "MicroStrategy"},
    {"ticker": "SGEN",  "name": "Seagen"},
    {"ticker": "NTAP",  "name": "NetApp"},
    {"ticker": "WDC",   "name": "Western Digital"},
    {"ticker": "STX",   "name": "Seagate Technology"},
    {"ticker": "LOGI",  "name": "Logitech"},
    {"ticker": "ZBRA",  "name": "Zebra Technologies"},
    {"ticker": "EXPO",  "name": "Exponent"},
    {"ticker": "NOVT",  "name": "Novanta"},
    {"ticker": "PCVX",  "name": "Vaxcyte"},
    {"ticker": "RMBS",  "name": "Rambus"},
    {"ticker": "WOLF",  "name": "Wolfspeed"},
    {"ticker": "AMBA",  "name": "Ambarella"},
    {"ticker": "ACLS",  "name": "Axcelis Technologies"},
    {"ticker": "ONTO",  "name": "Onto Innovation"},
    {"ticker": "SITM",  "name": "SiTime"},
    {"ticker": "MTSI",  "name": "MACOM Technology"},
]

KOSPI_100 = [
    {"ticker": "005930.KS", "name": "삼성전자"},
    {"ticker": "000660.KS", "name": "SK하이닉스"},
    {"ticker": "207940.KS", "name": "삼성바이오로직스"},
    {"ticker": "005380.KS", "name": "현대차"},
    {"ticker": "000270.KS", "name": "기아"},
    {"ticker": "068270.KS", "name": "셀트리온"},
    {"ticker": "035420.KS", "name": "NAVER"},
    {"ticker": "051910.KS", "name": "LG화학"},
    {"ticker": "006400.KS", "name": "삼성SDI"},
    {"ticker": "028260.KS", "name": "삼성물산"},
    {"ticker": "012330.KS", "name": "현대모비스"},
    {"ticker": "066570.KS", "name": "LG전자"},
    {"ticker": "003550.KS", "name": "LG"},
    {"ticker": "032830.KS", "name": "삼성생명"},
    {"ticker": "017670.KS", "name": "SK텔레콤"},
    {"ticker": "030200.KS", "name": "KT"},
    {"ticker": "086790.KS", "name": "하나금융지주"},
    {"ticker": "105560.KS", "name": "KB금융"},
    {"ticker": "055550.KS", "name": "신한지주"},
    {"ticker": "034730.KS", "name": "SK"},
    {"ticker": "005490.KS", "name": "POSCO홀딩스"},
    {"ticker": "003670.KS", "name": "포스코퓨처엠"},
    {"ticker": "009150.KS", "name": "삼성전기"},
    {"ticker": "018260.KS", "name": "삼성에스디에스"},
    {"ticker": "096770.KS", "name": "SK이노베이션"},
    {"ticker": "011200.KS", "name": "HMM"},
    {"ticker": "010130.KS", "name": "고려아연"},
    {"ticker": "000810.KS", "name": "삼성화재"},
    {"ticker": "047050.KS", "name": "포스코인터내셔널"},
    {"ticker": "009830.KS", "name": "한화솔루션"},
    {"ticker": "010950.KS", "name": "S-Oil"},
    {"ticker": "024110.KS", "name": "기업은행"},
    {"ticker": "000100.KS", "name": "유한양행"},
    {"ticker": "035720.KS", "name": "카카오"},
    {"ticker": "352820.KS", "name": "하이브"},
    {"ticker": "036570.KS", "name": "엔씨소프트"},
    {"ticker": "251270.KS", "name": "넷마블"},
    {"ticker": "006800.KS", "name": "미래에셋증권"},
    {"ticker": "032640.KS", "name": "LG유플러스"},
    {"ticker": "011070.KS", "name": "LG이노텍"},
    {"ticker": "161390.KS", "name": "한국타이어앤테크놀로지"},
    {"ticker": "051900.KS", "name": "LG생활건강"},
    {"ticker": "090430.KS", "name": "아모레퍼시픽"},
    {"ticker": "011170.KS", "name": "롯데케미칼"},
    {"ticker": "004020.KS", "name": "현대제철"},
    {"ticker": "000720.KS", "name": "현대건설"},
    {"ticker": "010140.KS", "name": "삼성중공업"},
    {"ticker": "042660.KS", "name": "한화오션"},
    {"ticker": "329180.KS", "name": "HD현대중공업"},
    {"ticker": "267250.KS", "name": "HD현대"},
    {"ticker": "078930.KS", "name": "GS"},
    {"ticker": "071050.KS", "name": "한국금융지주"},
    {"ticker": "015760.KS", "name": "한국전력"},
    {"ticker": "000830.KS", "name": "삼성C&T"},
    {"ticker": "316140.KS", "name": "우리금융지주"},
    {"ticker": "003490.KS", "name": "대한항공"},
    {"ticker": "020150.KS", "name": "롯데에너지머티리얼즈"},
    {"ticker": "034020.KS", "name": "두산에너빌리티"},
    {"ticker": "064350.KS", "name": "현대로템"},
    {"ticker": "012450.KS", "name": "한화에어로스페이스"},
]
